on:
  push:
  workflow_dispatch:

jobs:
  magic_pod_job:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install argparse
      - name: Prepare testplan
        env:
          TESTRAIL_URL: ${{ secrets.TESTRAIL_URL }}
          TESTRAIL_USER: ${{ secrets.TESTRAIL_USER }}
          TESTRAIL_PASSWORD: ${{ secrets.TESTRAIL_PASSWORD }}
        run: python testrail_prepare.py
      - name: Batch run test
        env:
          MAGICPOD_API_TOKEN: ${{ secrets.MAGICPOD_API_TOKEN }}
        run: bash run_magicpod_test.sh
